import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './Component/Navbar/Navbar'
import ClientOnly from './Component/ClientOnly'
import Modal from './Component/Modals/Modal'
import ToasterProvider from './Provider/ToasterProvider'
import RegisterModal from './Component/Modals/RegisterModal'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientOnly>
          <ToasterProvider/>
          <RegisterModal />
          <Navbar />   
        </ClientOnly>
        {children}
      </body>
    </html>
  )
}
